// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserCommand = { "type": "get_user", id: string, } | { "type": "save_user", id: string, name: string, role: string, };
