// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppVersion } from "../../../rust-core/bindings/AppVersion";
import type { User } from "../../../rust-core/bindings/User";

/**
 * ⚠️ ARCHITECTURE NOTE FOR DEVELOPERS:
 * For any struct (e.g., User, AppVersion) to be added to this mock registry and auto-exported
 * to TypeScript, the source struct MUST implement `#[derive(ts_rs::TS)]`.
 *
 * If the struct belongs to a 3rd-party closed crate without `#[derive(TS)]`, you can either:
 * 1. Use `#[ts(type = "string")]` or `#[ts(as = "...")]` on the corresponding field.
 * 2. Map the struct using a local transparent wrapper with `#[serde(transparent)]`.
 */
export type GlobalTypesMock = { user: User, app_version: AppVersion, };
