// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BridgeError = { "kind": "not_found", id: string, } | { "kind": "factorial_overflow", n: string, } | { "kind": "invalid_argument", reason: string, } | { "kind": "invalid_command", reason: string, } | { "kind": "internal", reason: string, } | { "kind": "serialization", reason: string, } | { "kind": "storage", reason: string, };
