// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathCommand } from "./MathCommand";
import type { SystemCommand } from "./SystemCommand";
import type { UserCommand } from "./UserCommand";

/**
 * Every command the bridge accepts. `callRust()` in TypeScript takes exactly
 * this type, so command names and args are checked against this enum at
 * compile time — the TS type *is* the wire format.
 */
export type BridgeCommand = { "cmd": "system", "args": SystemCommand } | { "cmd": "math", "args": MathCommand } | { "cmd": "user", "args": UserCommand };
