// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathResponses } from "./MathResponses";
import type { SystemResponses } from "./SystemResponses";
import type { UserResponses } from "./UserResponses";

/**
 * Type-only: the `data` type of every command, as `[cmd][type]`. `callRust()`
 * infers its return type from this, so it can't drift from the Rust side.
 */
export type BridgeResponses = { system: SystemResponses, math: MathResponses, user: UserResponses, };
