// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Points the core at the app's writable data directory (the native module's
 * `dataDir` constant). Loads saved users from there and persists new ones.
 */
export type Init = { data_dir: string, };
