// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddNumbers } from "./AddNumbers";
import type { Factorial } from "./Factorial";

export type MathCommand = { "type": "add_numbers" } & AddNumbers | { "type": "factorial" } & Factorial;
