// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppVersion } from "./AppVersion";

export type SystemResponses = { ping: string, get_version: AppVersion, init: null, };
