// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GetVersion } from "./GetVersion";
import type { Init } from "./Init";
import type { Ping } from "./Ping";

export type SystemCommand = { "type": "ping" } & Ping | { "type": "get_version" } & GetVersion | { "type": "init" } & Init;
